name: TRS Upload

on:
  repository_dispatch:
    types: [trs_upload]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Decode file
        run: |
          echo "${{ github.event.client_payload.content }}" | base64 -d > "${{ github.event.client_payload.filename }}"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.event.client_payload.release }}"
          files: "${{ github.event.client_payload.filename }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
